[build]
functions = "functions"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"

[[plugins]]
package = "netlify-plugin-algolia-index"
  [plugins.inputs]
  exclude = ['''/^\/tag\/.*/''']